<?xml version="1.0"?>
<robot xmlns:xacro = "https://www.ros.org/wiki/xacro">

  <xacro:property name="camera_size" value="0.025"/>

  <!-- Camera -->

    <link name="camera_link">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="${camera_size} ${camera_size} ${camera_size}"/>
          </geometry>
        </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${camera_size} ${camera_size} ${camera_size}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="0.5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="${(camera_size * camera_size) / 6}" ixy="0" ixz="0" iyy="${(camera_size * camera_size) / 6}" iyz="0" izz="${(camera_size * camera_size) / 6}" />
    </inertial>
  </link>

  <!-- Joint -->

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${(body_l / 2)} -0.1 0.06" rpy="0 0 0"/>
    <parent link="link_chassis"/>
    <child link="camera_link"/>
  </joint>

  <!-- Gazebo tags -->

  <gazebo reference="camera_link">
    <material>Gazebo/Red</material>
    <sensor type="camera" name="camera">

      <update_rate>30.0</update_rate>

      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>800</width>
          <height>800</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>

      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>robot_1/camera</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera_link</frameName>
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>

    </sensor>

  </gazebo>

</robot>