<?xml version="1.0"?>
<robot xmlns:xacro = "https://www.ros.org/wiki/xacro">

    <xacro:property name = "imu_size" value = "0.051"/>

    <!-- Link for IMU -->

    <link name = "imu_link">
        <collision> 
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <geometry>
                <box size = "${imu_size} ${imu_size} ${imu_size}"/>
            </geometry>     
        </collision>

        <inertial>
            <mass value = "0.0001"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <inertia 
                ixx = "${(0.0001 * imu_size * imu_size) / 6}"
                ixy = "0"
                ixz = "0"
                iyy = "${(0.0001 * imu_size * imu_size) / 6}"
                iyz = "0"
                izz = "${(0.0001 * imu_size * imu_size) / 6}"
                    />
        </inertial>  

        <visual>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <geometry>
                <box size = "${imu_size} ${imu_size} ${imu_size}"/>
            </geometry>
        </visual>
    </link>

    <!-- Joining IMU with link_chassis -->

    <joint name = "imu_joint" type = "fixed">
        <axis xyz="0 1 0"/> 
        <origin xyz="0 0 0" rpy = "0 0 0"/>
        <parent link="link_chassis"/>
        <child link="imu_link"/>
    </joint>

    <!-- Gazebo tags -->

    <gazebo reference="imu_link">
        <gravity>true</gravity>
        <sensor name="imu_sensor" type="imu">
        <always_on>true</always_on>
        <update_rate>100</update_rate>
        <visualize>true</visualize>
        <topic>imu_data</topic>

        <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
            <topicName>imu_data</topicName>
            <bodyName>imu_link</bodyName>
            <updateRateHZ>10.0</updateRateHZ>
            <gaussianNoise>0.0</gaussianNoise>
            <xyzOffset>0 0 0</xyzOffset>
            <rpyOffset>0 ${pi/2} 0</rpyOffset>
            <frameName>imu_link</frameName>
            <initialOrientationAsReference>false</initialOrientationAsReference>
      </plugin>

      <pose>0 0 0 0 0 0</pose>
    </sensor>
  </gazebo>

  </robot>