<?xml version="1.0"?>
<robot xmlns:xacro = "https://www.ros.org/wiki/xacro">

    <xacro:property name="kinect_size" value="0.025"/>

    <!-- Making a kinect Link-->

    <link name="kinect_link">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <box size="${kinect_size} ${kinect_size} ${kinect_size}"/>
          </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${kinect_size} ${kinect_size} ${kinect_size}"/>
            </geometry>
            <material name="red"/>
        </visual>

        <inertial>
            <mass value="0.5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="${(kinect_size * kinect_size) / 6}" ixy="0" ixz="0" iyy="${(kinect_size * kinect_size) / 6}" iyz="0" izz="${(kinect_size * kinect_size) / 6}" />
        </inertial>
    </link>

    <!-- Forming joint for kinect and link_chassis -->

    <joint name="kinect_joint" type="fixed">
        <axis xyz="0 1 0" />
        <origin xyz="${(body_l / 2)} 0 0.06" rpy="0 0 0"/>
        <parent link="link_chassis"/>
        <child link="kinect_link"/>
    </joint>

    <!-- Gazebo tags -->

    <gazebo reference="kinect_link">

        <sensor name="kinect_link_camera" type="depth">

            <update_rate>20</update_rate>

            <camera>
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>800</width>
                    <height>800</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>3</far>
                </clip>
            </camera>

            <plugin name="kinect_link_controller" filename="libgazebo_ros_openni_kinect.so">
                <baseline>0.2</baseline>
                <alwaysOn>true</alwaysOn>
                <updateRate>1.0</updateRate>
                <cameraName>kinect_link_camera_ir</cameraName>
                <imageTopicName>/kinect_link_camera/color/image_raw</imageTopicName>
                <cameraInfoTopicName>/kinect_link_camera/color/camera_info</cameraInfoTopicName>
                <depthImageTopicName>/kinect_link_camera/depth/image_raw</depthImageTopicName>
                <depthImageCameraInfoTopicName>/kinect_link_camera/depth/camera_info</depthImageCameraInfoTopicName>
                <pointCloudTopicName>/kinect_link_camera/depth/points</pointCloudTopicName>
                <frameName>kinect_link</frameName>
                <pointCloudCutoff>0.5</pointCloudCutoff>
                <pointCloudCutoffMax>3.0</pointCloudCutoffMax>
                <distortionK1>0.00000001</distortionK1>
                <distortionK2>0.00000001</distortionK2>
                <distortionK3>0.00000001</distortionK3>
                <distortionT1>0.00000001</distortionT1>
                <distortionT2>0.00000001</distortionT2>
                <CxPrime>0</CxPrime>
                <Cx>0</Cx>
                <Cy>0</Cy>
                <focalLength>0</focalLength>
                <hackBaseline>0</hackBaseline>
            </plugin>

        </sensor>

    </gazebo>

</robot>